-- Fictional demo catalog. Prices are kobo; images are illustrative placeholders.
insert into categories(name,slug) values ('Skincare','skincare'),('Makeup','makeup'),('Hair Care','hair-care'),('Fragrance','fragrance') on conflict(slug) do nothing;
insert into products(category_id,name,slug,short_description,description,ingredients,how_to_use,size_label,price_kobo,image_url,stock)
select c.id,v.name,v.slug,v.tagline,v.description,v.ingredients,v.usage,v.size,v.price,v.image,v.stock from (values
('skincare','Cudi Cloud Cleanser','cudi-cloud-cleanser','A gentle start to glowing days.','A soft daily facial cleanser that lifts away everyday impurities while leaving skin feeling comfortable. Suitable for morning and evening rituals.','Aqua, glycerin, coco-glucoside, panthenol, oat extract.','Massage onto damp skin for 30 seconds, then rinse. Avoid direct contact with eyes.','150 ml',650000,'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&auto=format&fit=crop',60),
('skincare','Cudi Dewdrop Moisturiser','cudi-dewdrop-moisturiser','Lightweight comfort, lasting softness.','A silky moisturiser designed to support your daily hydration routine without a heavy finish. Leaves skin looking fresh and feeling supple.','Aqua, glycerin, squalane, ceramides, sodium hyaluronate.','Apply a small amount to clean skin morning and evening. Patch test before first use.','50 ml',950000,'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop',45),
('skincare','Cudi Radiance Serum','cudi-radiance-serum','Your fresh-faced daily glow.','A lightweight serum for a simple routine focused on hydration and a more even-looking complexion. Layers comfortably under moisturiser.','Aqua, niacinamide, glycerin, sodium hyaluronate, allantoin.','Apply two to three drops to clean skin, followed by moisturiser. Patch test first.','30 ml',1250000,'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop',35),
('skincare','Cudi Daylight Sunscreen SPF 50','cudi-daylight-sunscreen','Everyday protection, a soft finish.','A daily broad-spectrum sunscreen with a comfortable finish. Designed to be the final step in your morning skincare ritual. Demo SPF claims must be validated before retail sale.','Aqua, approved UV filters, glycerin, vitamin E.','Apply generously 15 minutes before sun exposure. Reapply every two hours and after swimming or sweating.','50 ml',1100000,'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop',70),
('makeup','Cudi Velvet Lip Colour — Rose','cudi-velvet-lip-colour','A rose tint with a soft touch.','A creamy rose-toned lipstick with a satin finish. Build from a subtle wash to a confident everyday lip.','Castor oil, shea butter, carnauba wax, cosmetic pigments.','Apply directly to lips. Blot for a subtle finish or layer for richer colour.','3.5 g',450000,'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop',80),
('makeup','Cudi Second Skin Foundation — Cocoa','cudi-second-skin-foundation','Comfortable coverage that feels like you.','A buildable liquid foundation in a rich cocoa demo shade with a natural satin finish. Additional shades are a planned catalog expansion.','Aqua, dimethicone, glycerin, iron oxides, vitamin E.','Blend a small amount from the centre of the face outward using a brush or sponge.','30 ml',1450000,'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop',40),
('makeup','Cudi Flutter Mascara','cudi-flutter-mascara','Lift your everyday look.','A defining black mascara for softly separated lashes. A tapered brush makes a polished everyday finish simple.','Aqua, beeswax, carnauba wax, black cosmetic pigments.','Sweep from lash roots to tips. Do not share; replace three months after opening.','10 ml',550000,'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&auto=format&fit=crop',55),
('makeup','Cudi Petal Cream Blush','cudi-petal-cream-blush','A little warmth, a lovely glow.','A blendable warm terracotta cream blush that melts into your look. Wear lightly for a fresh finish or build the colour your way.','Jojoba oil, shea butter, candelilla wax, cosmetic pigments.','Tap onto cheeks with clean fingertips and blend outward.','5 g',600000,'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop',65),
('hair-care','Cudi Soft Wash Shampoo','cudi-soft-wash-shampoo','A fresh start for every wash day.','A gentle shampoo that cleanses the scalp and hair without a stripped feeling. Made for an easy wash-day routine.','Aqua, cocamidopropyl betaine, aloe extract, panthenol.','Massage into wet scalp, work through hair, and rinse thoroughly.','250 ml',650000,'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&auto=format&fit=crop',50),
('hair-care','Cudi Silk Knot Conditioner','cudi-silk-knot-conditioner','Slip, softness, and simpler detangling.','A rich rinse-out conditioner for smooth detangling and soft lengths. A comforting companion to your wash-day essentials.','Aqua, cetyl alcohol, shea butter, argan oil, glycerin.','Apply to clean wet hair from mid-lengths to ends. Leave for three minutes, detangle gently, and rinse.','250 ml',700000,'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop',50),
('hair-care','Cudi Golden Hair Oil','cudi-golden-hair-oil','A finishing touch of shine.','A nourishing oil blend for sealing moisture and adding shine to lengths and ends. Use a little at a time to find your perfect finish.','Jojoba oil, argan oil, sweet almond oil, vitamin E.','Warm a few drops between palms and smooth through damp or dry hair. Contains nut-derived oils.','100 ml',850000,'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=800&auto=format&fit=crop',42),
('hair-care','Cudi Curl Hug Leave-in','cudi-curl-hug-leave-in','Soft definition for your natural texture.','A lightweight leave-in cream to make curls and coils feel soft and manageable. Designed to fit into your own styling ritual.','Aqua, aloe vera, shea butter, glycerin, panthenol.','Apply to damp hair in sections. Finger-detangle and style as usual; do not rinse.','200 ml',800000,'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800&auto=format&fit=crop',48),
('fragrance','Cudi Rose Hour Eau de Parfum','cudi-rose-hour-eau-de-parfum','Soft rose, warm evenings.','A fictional floral fragrance opening with pear, settling into rose petals, and finishing with a warm musk accord. For a little everyday elegance.','Alcohol denat., parfum, aqua; pear, rose and musk fragrance accords.','Spray lightly onto pulse points. Flammable; avoid eyes and irritated skin.','50 ml',2500000,'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop',30),
('fragrance','Cudi Amber Dusk Eau de Parfum','cudi-amber-dusk-eau-de-parfum','Warm amber, quietly confident.','A fictional woody amber fragrance with a bright bergamot opening and a soft vanilla finish. An inviting scent for special moments.','Alcohol denat., parfum, aqua; bergamot, cedar, amber and vanilla accords.','Spray onto pulse points from a short distance. Keep away from heat and flames.','100 ml',4500000,'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop',22),
('fragrance','Cudi Fresh Bloom Body Mist','cudi-fresh-bloom-body-mist','A fresh little pick-me-up.','A light fictional body mist with citrus and white floral notes. Easy to refresh throughout the day for a soft scent.','Aqua, alcohol denat., parfum, glycerin; citrus and white floral accords.','Mist lightly over the body, avoiding face and broken skin. Keep away from flames.','150 ml',350000,'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&auto=format&fit=crop',90),
('fragrance','Cudi Coconut Daydream Mist','cudi-coconut-daydream-mist','A sunny moment, wherever you are.','A playful fictional body mist blending coconut, soft vanilla, and a clean musk finish. Light enough for everyday wear.','Aqua, alcohol denat., parfum; coconut, vanilla and musk accords.','Spray lightly onto skin after bathing. Avoid eyes and keep away from heat.','150 ml',400000,'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&auto=format&fit=crop',75)
) as v(category,name,slug,tagline,description,ingredients,usage,size,price,image,stock) join categories c on c.slug=v.category on conflict(slug) do nothing;
